platform :ios, '15.0'

target 'StapeSampleApp' do
  use_frameworks!
  
  pod 'FirebaseAnalytics'
end

target 'StapeSDK' do
  use_frameworks!

  target 'StapeSDKTests' do
    pod 'InstantMock'
    pod 'Nimble'
  end
end
