# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StapeSampleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StapeSampleApp

end

target 'StapeSDK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StapeSDK

  target 'StapeSDKTests' do
    # Pods for testing
  end

end
